on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    steps:
      - name: "Write Info"
        run:  echo "Server Name ${{ vars.SQLInstanceName }} "
      - uses: actions/checkout@v4.1.7
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build AdventureWorks DACPAC
        run: msbuild AdventureWorks/AdventureWorks.sqlproj
      - name: Copy DACPAC for Deployment
        run: |
          if ((test-path .\DACPACs) -eq $false)
          {
            mkdir .\DACPACs
          }
          else
          {  
            remove-item *.dacpac
          }
          get-childItem -recurse AdventureWorks -Filter "*.dacpac" | copy-item -Destination .\DACPACs
      - name: Deploy DACPAC
        run: sqlpackage.exe /SourceFile:".\DACPACs\AdventureWorks.dacpac" /action:publish /TargetConnectionString:"Server=${{ vars.SQLInstanceName }};Database=AdventureWorks2022;Integrated Security=SSPI;Encrypt=false"
