name: Test Deployment
on: 
  push: 
    branches:
      - dev
  workflow_dispatch:

jobs:
  call-template:
    uses: endlessautomation/dbdemos/.github/workflows/dbdeploytemplate.yml@main
    with:
      environment: "test"
