name: TestADFDeployment

on:
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: windows-latest
    steps:
      - name: Azure Data Factory Deploy
        # You may pin to the exact commit or the version.
        #uses: TrueNorthDataServices/ADFAutoDeploy@010d05427cd243c898bf304ef0dce7af8191d8ad
        uses: TrueNorthDataServices/ADFAutoDeploy@latest
          
