name: Deploy to Test

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: Test
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build AdventureWorks DACPAC
        run: msbuild Demos\SQLSatATL\AdventureWorks\AdventureWorks.sqlproj
      - name: Deploy DACPAC
        run: sqlpackage.exe /SourceFile:"Demos\SQLSatATL\AdventureWorks\bin\debug\AdventureWorks.dacpac" /action:publish /TargetConnectionString:"Server=localhost;Database=AWTest;Integrated Security=SSPI;Encrypt=false"
